=== Zake-hub/insy-5ahit-2019-laufmesser/Theorie/XMLSchemas/src/schema/searchconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="andOrType">
        <xs:choice maxOccurs="2">
            <xs:element name="or" type="andOrType"/>
            <xs:element name="and" type="andOrType"/>
            <xs:element name="term" type="xs:string"/>
            <xs:element name="not" type="searchType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="searchType">
        <xs:choice>
            <xs:element name="or" type="andOrType"/>
            <xs:element name="and" type="andOrType"/>
            <xs:element name="term" type="xs:string"/>
            <xs:element name="not" type="searchType"/>
        </xs:choice>
    </xs:complexType>

    <xs:element name="search" type="searchType"/>

</xs:schema>

=== Zake-hub/insy-5ahit-2019-laufmesser/Theorie/XMLSchemas/src/xml/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<search xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../schema/searchconf.xsd">
    <or>
        <and>
            <term>x + 2</term>
            <or>
                <term>y - 1</term>
                <not>
                    <term>k + 3</term>
                </not>
            </or>
        </and>
    </or>
</search>
